# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: warehouse.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'warehouse.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fwarehouse.proto\x12\x03llm\"\x1e\n\nAskRequest\x12\x10\n\x08question\x18\x01 \x01(\t\"\x1d\n\x0b\x41skResponse\x12\x0e\n\x06\x61nswer\x18\x01 \x01(\t2i\n\nLLMService\x12(\n\x03\x41sk\x12\x0f.llm.AskRequest\x1a\x10.llm.AskResponse\x12\x31\n\x0c\x41skScientist\x12\x0f.llm.AskRequest\x1a\x10.llm.AskResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'warehouse_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ASKREQUEST']._serialized_start=24
  _globals['_ASKREQUEST']._serialized_end=54
  _globals['_ASKRESPONSE']._serialized_start=56
  _globals['_ASKRESPONSE']._serialized_end=85
  _globals['_LLMSERVICE']._serialized_start=87
  _globals['_LLMSERVICE']._serialized_end=192
# @@protoc_insertion_point(module_scope)
